# Welcome to Jekyll!
#

# Site settings
title: ExSpendables
description: |
  Save Money  
  Track Money  
  Monitor Expenses
owner: Team SKY-NET # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "/isee2019-Sky-Net" # the subpath of your site, e.g. /blog
url: "https://dbse-teaching.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/AbhivanthAltair
  github: https://dbse-teaching.github.io/isee2019-Sky-Net/
  linkedin-square: https://www.linkedin.com/in/harish-kumar-harihara-subramanian-111180140/
  facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
